driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6
  - name: centos-7
  - name: debian-7
    run_list: apt::default
  - name: debian-8
    run_list: apt::default
  - name: debian-9
    run_list: apt::default
  - name: fedora-26
  - name: opensuse-leap-42
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default

suites:
- name: default
  run_list:
    - recipe[erlang]

- name: gui_tools
  run_list:
    - recipe[erlang]
  attributes:
    erlang:
      gui_tools: true
  excludes:
    - centos-6
    - centos-7
    - fedora-26

- name: esl
  run_list:
    - recipe[erlang::esl]
  excludes:
    - fedora-26
    - opensuse-42

- name: source
  run_list:
    - recipe[erlang::source]
